### ISSUE TITLE
error when 'npm start'

### ISSUE THREAD

**Issue by msman** [aichbauer/express-rest-api-boilerplate#2]
express-rest-api-boilerplate@0.0.0 drop-sqlite-db 
> rm ./db/database.sqlite

'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by aichbauer** [comment]
What OS are you using?

**Comment by msman** [comment]
I use Windows OS.
Note: I chose mysql2

**Comment by aichbauer** [comment]
for windows the command would be `del` and not `rm`. 

I will add support for windows as soon as possible...
