### ISSUE TITLE
Routes not working

### ISSUE THREAD

**Issue by nileshlets** [aichbauer/express-rest-api-boilerplate#21]
I have configured MySql but routes are not working. Getting 'Cannot GET /route name ' error on every route. What am I missing in the configuration installation?

**Comment by aichbauer** [comment]
Seems that you use a `get request` for a `post request` route? But without any additional information about what you want to achieve (how your routes file look like, to what functions and controllers your routes point at, etc...) I can not help you.

**Comment by nileshlets** [comment]
I have installed and configured the code. Then I try post route 'http://localhost:PORT/login' it shows 'Cannot POST /api/login'. I haven't changed anything except configuration. Can you guide what I am missing here? PFA image of my console. It shows running
![capture](https://user-images.githubusercontent.com/8393079/43072380-83bb1e8c-8e93-11e8-9d81-d8d63ec3aa92.PNG)
 properly.

**Comment by aichbauer** [comment]
how do you access this route? with js in your clientside code or with postman? can you show the code?

**Comment by aichbauer** [comment]
you have to access the routes like `localhost:port/public/login`
