### ISSUE TITLE
One-To-Many Association

### ISSUE THREAD

**Issue by ricardommps** [aichbauer/express-rest-api-boilerplate#22]
How to create an association in this structure?

**Comment by aichbauer** [comment]
This is probably a better question for [stackoverflow](https://stackoverflow.com/). 

Take a look at this boilerplate (it may differ in the controllers but it does not with models).

[User](https://github.com/aichbauer/express-graphql-boilerplate/blob/master/api/models/User.js) has many [Notes](https://github.com/aichbauer/express-graphql-boilerplate/blob/master/api/models/Note.js).

So basically `const { Note } = require('./Note');` you import the other Model. and than you `User.hasMany(Note, { as: 'notes', foreignKey: 'userId' });` add it to the model.

Take a look at the [Sequelize docs](http://docs.sequelizejs.com/manual/tutorial/associations.html)
