### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by ianninirojas** [aichbauer/express-rest-api-boilerplate#26]
Hi! I'm triying run the project but I have this error
/express-rest-api-boilerplate/api/api.js:26
const mappedOpenRoutes = mapRoutes(config.publicRoutes, 'api/controllers/');
                         ^

TypeError: mapRoutes is not a function

Thanks

**Comment by ace3** [comment]
for temporary solution, you can change this on package.js

"express-routes-mapper": "^1.0.2",

remove the ^ , then do clean npm install.

**Comment by aichbauer** [comment]
@ianninirojas What @ace3 says is probably the best solution right now, we are working on a fix in `express-routes-mapper`.

**Comment by ianninirojas** [comment]
It's work thank you!

**Comment by aichbauer** [comment]
aichbauer/express-routes-mapper#25

This should fix this behaviour. It should be possible to use `^1.0.2` again as soon as this PR gets merged and the new version is published.

**Comment by aichbauer** [comment]
Problem should be fixed due to the merge of: [aichbauer/express-routes-mapper#25](https://github.com/aichbauer/express-routes-mapper/pull/25)
