### ISSUE TITLE
Wrap your tests is a `describe` block...

### ISSUE THREAD

**Issue by mswezey23** [aichbauer/express-rest-api-boilerplate#31]
...otherwise each `test` block runs in parallel within the test file. This can cause a race condition leading to some test cases failing.

```
describe('Test Description', () => {
    test()
    test()
})
```

**Comment by mswezey23** [comment]
I ran into that issue when using MySql. 

Also, I had to add this argument `--runInBand` to make jest not run in parallel due to the DB being the choke point

**Comment by aichbauer** [comment]
Hey @mswezey23, thanks for your issue. I hope I can help.

Could you provide a more detailed example? Right know we try to use a new database entry for every test which is the most reliable thing when running tests in parallel with a database entries, but I am not a expert on this matter.

When you run tests with `--runInBand` the tests will take longer, which may not a issue for a small program, but if you end up with a couple hundred tests you may want to run tests in parallel. I am not a expert on testing, but I think you can increase performance and resolve the problem of your flaky test with creating and and deleting database entries only used for this test. In the next example we create a user test the login and then delete the user, to not have a problem with other tests. Off course there can always be a problem somewhere, but without further looking into your code I do not exactly know how to help you.

```js
test('User | login', async () => {
  const user = await User.create({
    email: 'martin@mail.com',
    password: 'securepassword',
  });

  const res = await request(api)
    .post('/public/login')
    .set('Accept', /json/)
    .send({
      email: 'martin@mail.com',
      password: 'securepassword',
    })
    .expect(200);

  expect(res.body.token).toBeTruthy();

  expect(user).toBeTruthy();

  await user.destroy();
});
```

**Comment by aichbauer** [comment]
Close due to no response
