### ISSUE TITLE
NODE_ENV is undefined

### ISSUE THREAD

**Issue by ashish00076** [aichbauer/express-rest-api-boilerplate#33]
Looks like the `process.env.NODE_ENV`  is being set to undefined.

The cross-env doesn't seem to function properly from the scripts.

I'm trying to set the flag as development, but getting undefined, and an error as below -

`only development, staging, test and production are valid NODE_ENV variables but undefined is specified`

Kindly suggest solution.

**Comment by aichbauer** [comment]
Hey @ashish00076,

thanks for the issue...

Would you mind to share a bit more details?

Node version, if you are using yarn or npm to start the command. What the command was that you executed. Can you share your package.json? Have you installed all the packages with `npm i` or `yarn`?

**Comment by ashish00076** [comment]
Hey @aichbauer ,

I found the cause.

I was running the project with **Visual Studio Code in debugging mode**, hence it couldn't detect environment.
Devised a workaround for the same by creating a config in VS Code `launch.json`. This solved the issue. Now I can run the project in debugging mode too.

Thank you.

Regards,
**Ashish Deshpande**
