### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by anjil** [aichbauer/express-rest-api-boilerplate#38]
I am getting below error with **npm start**

```
> express-rest-api-boilerplate@0.0.0 start D:\express-rest-api-boilerplate-master
> npm run nodemon


> express-rest-api-boilerplate@0.0.0 nodemon D:\express-rest-api-boilerplate-master
> nodemon --exec npm run dev

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run dev`

> express-rest-api-boilerplate@0.0.0 dev D:\express-rest-api-boilerplate-master
> cross-env NODE_ENV=development node ./api/api.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es6.object.define-property'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\express-rest-api-boilerplate-master\node_modules\express-routes-mapper\lib\index.js:5:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-rest-api-boilerplate@0.0.0 dev: `cross-env NODE_ENV=development node ./api/api.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-rest-api-boilerplate@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2019-06-26T00_32_12_101Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

```

I am runnung node 8 on windows 10.

Please help.
Thanks in advance

**Comment by ace3** [comment]
can you  check what version of babel & core-js you have.

usually the problem is in babel version.

**Comment by anjil** [comment]
@ace3 , Thanks for looking at the issue. Please take a look at below details:

> node.js v10.14.2
> npm v6.4.1
> core-js v3.1.4
> babel 7.4.5 (@babel/core 7.4.5)

https://gist.github.com/anjil/756e30bc14b64abc0fae2f4034802af0

**Comment by ace3** [comment]
hi @anjil , can you try to downgrade core-js to => core-js^2.6.9

**Comment by anjil** [comment]
> core-js^2.6.9

I don't see any dependency added in the package.json file for core-js. 
I think its a dependency of some other module. do you want me to add it via below command

npm install core-js@^2.6.9

Please let me know if there is any other way of doing it..

**Comment by ace3** [comment]
it's dependencies from babel i think.
do you have core-js installed globally ? try to downgrade global npm package.

**Comment by anjil** [comment]
@ace3 , I ran npm install core-js@^2.6.9 and it solved the issue.
I think this entry should go into the package.json file.

Thanks for help, happy coding

**Comment by ace3** [comment]
@anjil , glad it worked out well. 

cheers.

**Comment by aichbauer** [comment]
@ace3 thank you for support, I appreciate it 👍
