### ISSUE TITLE
How to not have the DB reset upon starting server?

### ISSUE THREAD

**Issue by Orest-Cokan** [aichbauer/express-rest-api-boilerplate#44]
Hi, 

How would I go about not having the DB reset upon starting the server? cheers

**Comment by ace3** [comment]
hi @Orest-Cokan , you can open **/api/services/db.service.js** and remove / comment in line 34 
**await dropDB();** to disable it permanently.

**Comment by Orest-Cokan** [comment]
Thanks, completely overlooked that part.
