### ISSUE TITLE
What are the routes for signin/signup ? no documentation on that

### ISSUE THREAD

**Issue by itamarzil123** [aichbauer/express-rest-api-boilerplate#45]

**Comment by itamarzil123** [comment]
It seems like 'public/validate' should be called from the client, before 'public/login' ? Am I correct? The project is great but a simple documentation on the flow is missing.
good luck (:

**Comment by itamarzil123** [comment]
Do I understand correctly ? /public/register is for signup.
/public/login is for login and getting a token.
then, for each API call the client will use that token and validate it by the route /public/validate results?

**Comment by aichbauer** [comment]
@itamarzil123 you can do so if you want... But you do not need to use `/public/validate` on each route... each route can have a middleware that runs before private routes, where you can validate your token... this would reduce the http request...

Yes `/public/register` is used for signup and `/public/login` is used for getting a token... this token should be sent with every request that requires to be authenticated.

so to access `'GET /users': 'UserController.getAll',` you need to send a token... If your token is valid it will return all users, but if your token is invalid you would get back a `401` as a statuscode with an error message.
