### ISSUE TITLE
Feat: update authentication to passport strategies

### ISSUE THREAD

**Issue by aichbauer** [aichbauer/express-rest-api-boilerplate#5]
If we use passport we could implement different authentication strategies with ease.

**Comment by aichbauer** [comment]
Closing this issue, because I, myself moved away from using passport. Feel free to open a new Issue if you think this could improve this project.

**Comment by pauloladimeji** [comment]
> Closing this issue, because I, myself moved away from using passport. Feel free to open a new Issue if you think this could improve this project.

curious to know what auth module you moved on to using...

**Comment by aichbauer** [comment]
@pauloladimeji Sorry for the late response... I myself got away from login strategies via FB, Google, Twitter, since I create mostly business applications where a JSON web token and a refresh token is mostly anything you need. But also for new hobby projects I got away for from other strategies, since JSON web tokens are self contained, no need for a third party... Of course if you want to use other strategies it would be better to rely on a library that provides easy use of them.
